### GENERAL SETTINGS ###

# Site settings
title: Cameron's Portfolio
description: "Cameron Bells Projects"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/"
url: www.cameronbell.co.uk

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#96C2DD" #"#db4025"
  primary_rgb: "150,194,221" #"219,64,37" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#96C2DD"
  link_hover: "#cae0ee"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: github
    url: https://github.com/CameronBell1337
  - title: twitter
    url: https://twitter.com/G4rf13ld_
  - title: instagram
    url:
  - title: linkedin
    url: https://www.linkedin.com/in/cameron-bell-b2169a176/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - United Kingdom.
email: cameron.bell33@live.co.uk



### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Cameron
    position: MSc Commercial Games Development Student
    text: Gamer, Programmer, Creator.
    img: me.jpg
    social:
      - title: envelope #use for email address
        url: mailto:cameron.bell33@live.co.uk
      - title: twitter
        url: https://twitter.com/G4rf13ld_
      - title: linkedin
        url: https://www.linkedin.com/in/cameron-bell-b2169a176/
 
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Game Player turned Game Creator."
