### GENERAL SETTINGS ###

# Site settings
title: UWEGAMES - Cameron Bell
description: "Games development from an n00b's persepective."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/"
url: https://CameronBell1337.github.io

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#edc834" #"#db4025"
  primary_rgb: "237,200,52" #"219,64,37" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#edd884"
  link_hover: "#edc834"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: github
    url: https://github.com/CameronBell1337
  - title: twitter
    url: https://twitter.com/Garf1eldCS
  - title: instagram
    url:
  - title: linkedin
    url: https://www.linkedin.com/in/cameron-bell-b2169a176/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - University of the West of England,
    - Frenchay Campus, Bristol, BS16 1QY,
    - United Kingdom.
email: cameron2.bell@live.uwe.ac.uk



### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Cameron
    position: Games Technology Student
    text: I am a cat!
    img: profile_2.jpg
    social:
      - title: envelope #use for email address
        url: mailto:cameron2.bell@live.uwe.ac.uk
      - title: twitter
        url: https://twitter.com/Garf1eldCS
      - title: linkedin
        url: https://www.linkedin.com/in/cameron-bell-b2169a176/
 
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Game Player turned Game Creator."
